# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@16.13.1
  aws-cli: circleci/aws-cli@2.0.0

jobs:
  frontend:
    
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: install dependancies
          command: npm run front:install

      - run:
          name: run build
          command: npm run front:build
      - run:
          name: run tests
          command: npm run front:test
          
      - aws-cli/install

      - run:
          name: deploy to aws
          command: $ aws s3 cp --recursive --acl public-read ./www s3://seifsudagram/


workflows:
  building_deploying: 
    jobs:
      - frontend
      
